includes:
  - from_url:
      url: charmbracelet/meta/main/goreleaser.yaml

variables:
  main: "./cmd/wishlist"
  description: "Confetty over SSH"
  github_url: "https://github.com/charmbracelet/confettysh"
  maintainer: "Carlos A Becker <carlos@charm.sh>"
  brew_commit_author_name: "Carlos A Becker"
  brew_commit_author_email: "carlos@charm.sh"
