name: nightly

on: [push, pull_request]

jobs:
  nightly:
    uses: charmbracelet/meta/.github/workflows/nightly.yml@main
    secrets:
      docker_username: ${{ secrets.DOCKERHUB_USERNAME }}
      docker_token: ${{ secrets.DOCKER_PASSWORD }}
      goreleaser_key: ${{ secrets.GORELEASER_KEY }}
